spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
